### ISSUE TITLE
Incorrect parsing of -3 ** 2

### ISSUE THREAD

**Issue by terpstra** [andychu/pratt-parsing-demo#1]
The parser in this repository would evaluate this expression as +9.

**Comment by andychu** [comment]
That's an interesting observation.  I probably got this from bash:

```
$ bash -c 'echo $(( -3 ** 2 ))'
9
$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
```

But yeah Python and R do the more sensible thing.

Arguably that is a bash bug.

**Comment by andychu** [comment]
NOTE: zsh and busybox ash both follow bash's behavior.

```
$ busybox ash -c 'echo $(( -3 ** 2 ))'                                        
9
```

**Comment by andychu** [comment]
Thanks for the report.  I just fixed this -- let me know if you notice any problems.

It looks like I did copy the table of precedences from `expr.c` in bash.  But I think it makes sense to follow what Python and R do.

**Comment by terpstra** [comment]
You're lucky you didn't demote negation to the same priority as normal '-', or I'd have had a follow-up issue: 2**-1*4. I do not like how Pratt parsers allow unary rules to decrease the precedence. It seems quite iffy. I prefer Haskell's solution: fail to parse if there is a priority inversion.

**Comment by andychu** [comment]
Not sure what you're talking about.  Send me a demo with the bug if you think it's interesting.
